language: R
pandoc_version: 1.17.2
cache: packages
repos:
  CRAN: https://cran.rstudio.com/
  KRAN: http://rweb.crmda.ku.edu/kran/
  
addons:
  apt:
    packages:
      - libxml2-dev
      - libproj-dev
      - libgdal-dev

before_script:
  - Rscript -e 'devtools::install_github("rstudio/blogdown")'
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e "blogdown::build_site()"
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh
