language: R
pandoc_version: 1.17.2
cache: packages
repos:
  CRAN: https://cran.rstudio.com/
  KRAN: http://rweb.crmda.ku.edu/kran/
  
addons:
  apt:
    packages:
      - libxml2-dev
      - libproj-dev
      - libgdal-dev

before_script:
  - Rscript -e 'devtools::install_github("rstudio/blogdown")'
  - Rscript -e 'blogdown::install_hugo(version = "0.56.3", extended = FALSE)'
  - Rscript -e "options(servr.daemon = TRUE); blogdown::serve_site()"
  - Rscript -e "blogdown::hugo_build()"
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh
