language: R
pandoc_version: 1.17.2
cache: packages
repos:
  CRAN: https://cran.rstudio.com/
  KRAN: http://rweb.crmda.ku.edu/kran/
  
addons:
  apt:
    packages:
      - libxml2-dev
      - libproj-dev
      - libgdal-dev

before_script:
  - Rscript -e 'blogdown::install_hugo(version = "latest")'
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh