baseurl = "http://www.samabbott.co.uk/"  # End your URL with a `/` trailing slash.
title = "Sam Abbott"
copyright = "&copy; 2018 Sam Abbott"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "samabbott-co-uk"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-85604924-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]
  
[blackfriday]
  hrefTargetBlank = true
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
  color_theme = "default"
  
    # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"
  
  name = "Sam Abbott"
  role = "PhD student and Data Scientist"
  organizations =  [ { name = "BIDD, University of Bristol", url = "http://www.bristol.ac.uk/social-community-medicine/research/groups/bidd/"},
  { name = "Funding Circle", url = "http://fundingcircle.com"}]
  
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"
  email = "contact@samabbott.co.uk"
  address = "BF8, Oakfield House, School of Social and Community Medicine, University of Bristol "
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""
  GithubEdit = "https://github.com/seabbs/seabbs.github.io/tree/sources/content/"
  description = "Personal blog: Writing about infectious disease epidemiology, peer to peer lending and R."
  twitterAuthor = "@seabbs"
  twitterSite = "@seabbs"
  
  logo = "logo.png"
  
    # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 0
  map_api_key = ""
  latitude = "51.4545"
  longitude = "-2.5879"
  zoom = 15


  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = "seabbs"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"


  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false
  
  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   For the list of supported languages and styles, see:
  #  
  #
  #   For more info on the highlighting options, see:
  #   https://sourcethemes.com/academic/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r", "python", "yaml"]
  highlight_style = "github"
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]
  
  
    # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = false

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true
  
      # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3
    
  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "contact@samabbott.co.uk"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/seabbs"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/seabbs/"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Sam_Abbott2"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/seabbs"
    
  [[params.social]]
    icon = "stack-overflow"
    icon_pack = "fa"
    link = "https://stackoverflow.com/users/9295446/sam-abbott"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true
  
[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 5
  
[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

[[menu.main]]
  name = "Tags"
  url = "#tags"
  weight = 8
  
[[menu.main]]
  name = "CV"
  url = "pdf/cv_sea.pdf"
  weight = 9
  
# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-uk"
